
export interface Game {
  id: string;
  name: string;
  provider: string;
  image: string;
  category: string;
  isHot?: boolean;
  isFavorite?: boolean;
  isVIP?: boolean;
  bgColor?: string;
  providerColor?: string;
  link?: string;
}

export const PROVIDERS = [
  { id: 'ALL', name: 'ALL', logo: 'https://placehold.co/100x40/111827/ffffff?text=ALL' },
  { id: 'JILI', name: 'JILI', logo: 'https://placehold.co/100x40/1e3a8a/ffffff?text=JILI' },
  { id: 'PG', name: 'PG', logo: 'https://placehold.co/100x40/ea580c/ffffff?text=PG' },
  { id: 'JBD', name: 'JBD', logo: 'https://placehold.co/100x40/047857/ffffff?text=JBD' },
  { id: 'SPRIBE', name: 'SPRIBE', logo: 'https://placehold.co/100x40/b91c1c/ffffff?text=SPRIBE' },
  { id: 'EVOLUTION', name: 'EVOLUTION', logo: 'https://placehold.co/100x40/000000/ffffff?text=EVO' },
  { id: 'PRAGMATIC', name: 'PRAGMATIC', logo: 'https://placehold.co/100x40/4338ca/ffffff?text=PP' },
  { id: 'BT GAME', name: 'BT GAME', logo: 'https://placehold.co/100x40/374151/ffffff?text=BT' },
];

export const games: Game[] = [
  // JILI (22)
  { id: 'jili_1', name: 'Super Ace', provider: 'JILI', image: 'https://picsum.photos/seed/jili1/400/600', category: 'স্লট', isHot: true, bgColor: 'from-yellow-600 to-green-600' },
  { id: 'jili_2', name: 'Golden Empire', provider: 'JILI', image: 'https://picsum.photos/seed/jili2/400/600', category: 'স্লট', isHot: true, bgColor: 'from-yellow-500 to-yellow-700' },
  { id: 'spribe_aviator', name: 'Aviator', provider: 'SPRIBE', image: 'https://picsum.photos/seed/aviator/400/600', category: 'ক্র্যাশ', isHot: true, bgColor: 'from-orange-600 to-orange-900' },
  { id: 'jili_3', name: 'Fortune Gems', provider: 'JILI', image: 'https://picsum.photos/seed/jili3/400/600', category: 'স্লট', isHot: true, bgColor: 'from-red-500 to-red-800' },
  { id: 'jili_4', name: 'Boxing King', provider: 'JILI', image: 'https://picsum.photos/seed/jili4/400/600', category: 'স্লট', isHot: true, bgColor: 'from-orange-500 to-red-600' },
  { id: 'jili_5', name: 'Money Coming', provider: 'JILI', image: 'https://picsum.photos/seed/jili5/400/600', category: 'স্লট', isHot: true, bgColor: 'from-green-500 to-green-800' },
  { id: 'jili_6', name: 'Charge Buffalo', provider: 'JILI', image: 'https://picsum.photos/seed/jili6/400/600', category: 'স্লট', bgColor: 'from-yellow-600 to-orange-800' },
  { id: 'jili_7', name: 'Magic Lamp', provider: 'JILI', image: 'https://picsum.photos/seed/jili7/400/600', category: 'স্লট', bgColor: 'from-purple-500 to-purple-800' },
  { id: 'jili_8', name: 'Ali Baba', provider: 'JILI', image: 'https://picsum.photos/seed/jili8/400/600', category: 'স্লট', bgColor: 'from-blue-500 to-blue-800' },
  { id: 'jili_9', name: 'Crazy 777', provider: 'JILI', image: 'https://picsum.photos/seed/jili9/400/600', category: 'স্লট', isHot: true, bgColor: 'from-red-600 to-yellow-600' },
  { id: 'jili_10', name: 'Seven Seven Seven', provider: 'JILI', image: 'https://picsum.photos/seed/jili10/400/600', category: 'স্লট', bgColor: 'from-red-500 to-red-700' },
  { id: 'jili_11', name: 'Roma X', provider: 'JILI', image: 'https://picsum.photos/seed/jili11/400/600', category: 'স্লট', bgColor: 'from-orange-600 to-red-800' },
  { id: 'jili_12', name: 'Jungle King', provider: 'JILI', image: 'https://picsum.photos/seed/jili12/400/600', category: 'স্লট', bgColor: 'from-green-600 to-green-900' },
  { id: 'jili_13', name: 'Crazy Hunter', provider: 'JILI', image: 'https://picsum.photos/seed/jili13/400/600', category: 'স্লট', bgColor: 'from-red-500 to-red-800' },
  { id: 'jili_14', name: 'Gem Party', provider: 'JILI', image: 'https://picsum.photos/seed/jili14/400/600', category: 'স্লট', isHot: true, bgColor: 'from-purple-400 to-purple-700' },
  { id: 'jili_15', name: 'Dragon Quest', provider: 'JILI', image: 'https://picsum.photos/seed/jili15/400/600', category: 'স্লট', bgColor: 'from-blue-600 to-blue-900' },
  { id: 'jili_16', name: 'Happy Taxi', provider: 'JILI', image: 'https://picsum.photos/seed/jili16/400/600', category: 'স্লট', bgColor: 'from-yellow-500 to-yellow-800' },
  { id: 'jili_17', name: 'Super Rich', provider: 'JILI', image: 'https://picsum.photos/seed/jili17/400/600', category: 'স্লট', isHot: true, bgColor: 'from-green-400 to-green-700' },
  { id: 'jili_18', name: 'Wild Ace', provider: 'JILI', image: 'https://picsum.photos/seed/jili18/400/600', category: 'স্লট', bgColor: 'from-orange-500 to-red-700' },
  { id: 'jili_19', name: 'Bao Boon Chin', provider: 'JILI', image: 'https://picsum.photos/seed/jili19/400/600', category: 'স্লট', bgColor: 'from-red-600 to-red-900' },
  { id: 'jili_20', name: 'Night City', provider: 'JILI', image: 'https://picsum.photos/seed/jili20/400/600', category: 'স্লট', bgColor: 'from-indigo-600 to-indigo-900' },
  { id: 'jili_21', name: 'SevenSevenSeven 2', provider: 'JILI', image: 'https://picsum.photos/seed/jili21/400/600', category: 'স্লট', bgColor: 'from-red-700 to-yellow-700' },
  { id: 'jili_22', name: 'Agent Ace', provider: 'JILI', image: 'https://picsum.photos/seed/jili22/400/600', category: 'স্লট', isHot: true, bgColor: 'from-gray-700 to-blue-900' },

  // PG (22)
  { id: 'pg_1', name: 'Mahjong Ways', provider: 'PG', image: 'https://picsum.photos/seed/pg1/400/600', category: 'স্লট', isHot: true, bgColor: 'from-red-600 to-red-900' },
  { id: 'pg_2', name: 'Mahjong Ways 2', provider: 'PG', image: 'https://picsum.photos/seed/pg2/400/600', category: 'স্লট', isHot: true, bgColor: 'from-red-500 to-red-800' },
  { id: 'pg_3', name: 'Treasure of Aztec', provider: 'PG', image: 'https://picsum.photos/seed/pg3/400/600', category: 'স্লট', isHot: true, bgColor: 'from-yellow-500 to-orange-700' },
  { id: 'pg_4', name: 'Lucky Neko', provider: 'PG', image: 'https://picsum.photos/seed/pg4/400/600', category: 'স্লট', isHot: true, bgColor: 'from-pink-500 to-purple-700' },
  { id: 'pg_5', name: 'Wild Bandito', provider: 'PG', image: 'https://picsum.photos/seed/pg5/400/600', category: 'স্লট', bgColor: 'from-purple-600 to-purple-900' },
  { id: 'pg_6', name: 'Dreams of Macau', provider: 'PG', image: 'https://picsum.photos/seed/pg6/400/600', category: 'স্লট', bgColor: 'from-blue-500 to-blue-800' },
  { id: 'pg_7', name: 'Caishen Wins', provider: 'PG', image: 'https://picsum.photos/seed/pg7/400/600', category: 'স্লট', bgColor: 'from-red-400 to-red-700' },
  { id: 'pg_8', name: 'Egypts Book', provider: 'PG', image: 'https://picsum.photos/seed/pg8/400/600', category: 'স্লট', bgColor: 'from-yellow-600 to-yellow-900' },
  { id: 'pg_9', name: 'Ganesha Fortune', provider: 'PG', image: 'https://picsum.photos/seed/pg9/400/600', category: 'স্লট', bgColor: 'from-orange-500 to-orange-800' },
  { id: 'pg_10', name: 'Double Fortune', provider: 'PG', image: 'https://picsum.photos/seed/pg10/400/600', category: 'স্লট', bgColor: 'from-red-500 to-red-800' },
  { id: 'pg_11', name: 'Dragon Hatch', provider: 'PG', image: 'https://picsum.photos/seed/pg11/400/600', category: 'স্লট', bgColor: 'from-green-600 to-green-900' },
  { id: 'pg_12', name: 'Medusa', provider: 'PG', image: 'https://picsum.photos/seed/pg12/400/600', category: 'স্লট', bgColor: 'from-blue-600 to-blue-900' },
  { id: 'pg_13', name: 'Heist Stakes', provider: 'PG', image: 'https://picsum.photos/seed/pg13/400/600', category: 'স্লট', isHot: true, bgColor: 'from-gray-600 to-gray-900' },
  { id: 'pg_14', name: 'Candy Burst', provider: 'PG', image: 'https://picsum.photos/seed/pg14/400/600', category: 'স্লট', bgColor: 'from-pink-400 to-pink-700' },
  { id: 'pg_15', name: 'Phoenix Rises', provider: 'PG', image: 'https://picsum.photos/seed/pg15/400/600', category: 'স্লট', isHot: true, bgColor: 'from-orange-500 to-red-700' },
  { id: 'pg_16', name: 'Circus Delight', provider: 'PG', image: 'https://picsum.photos/seed/pg16/400/600', category: 'স্লট', bgColor: 'from-purple-500 to-purple-800' },
  { id: 'pg_17', name: 'Mahjong Ways 3', provider: 'PG', image: 'https://picsum.photos/seed/pg17/400/600', category: 'স্লট', isHot: true, bgColor: 'from-red-600 to-red-900' },
  { id: 'pg_18', name: 'Fortune Gods', provider: 'PG', image: 'https://picsum.photos/seed/pg18/400/600', category: 'স্লট', bgColor: 'from-yellow-400 to-yellow-700' },
  { id: 'pg_19', name: 'Gem Saviour', provider: 'PG', image: 'https://picsum.photos/seed/pg19/400/600', category: 'স্লট', bgColor: 'from-blue-400 to-blue-700' },
  { id: 'pg_20', name: 'Hood vs Wolf', provider: 'PG', image: 'https://picsum.photos/seed/pg20/400/600', category: 'স্লট', bgColor: 'from-red-400 to-gray-800' },
  { id: 'pg_21', name: 'Bikini Paradise', provider: 'PG', image: 'https://picsum.photos/seed/pg21/400/600', category: 'স্লট', bgColor: 'from-teal-400 to-blue-600' },
  { id: 'pg_22', name: 'Ways of Qilin', provider: 'PG', image: 'https://picsum.photos/seed/pg22/400/600', category: 'স্লট', isHot: true, bgColor: 'from-green-500 to-green-800' },

  // JBD (18)
  { id: 'jbd_1', name: 'Open Sesame', provider: 'JBD', image: 'https://picsum.photos/seed/jbd1/400/600', category: 'স্লট', bgColor: 'from-purple-500 to-purple-800' },
  { id: 'jbd_2', name: 'Super Niubi', provider: 'JBD', image: 'https://picsum.photos/seed/jbd2/400/600', category: 'স্লট', bgColor: 'from-red-500 to-red-800' },
  { id: 'jbd_3', name: 'Fortune Treasure', provider: 'JBD', image: 'https://picsum.photos/seed/jbd3/400/600', category: 'স্লট', bgColor: 'from-yellow-500 to-yellow-800' },
  { id: 'jbd_4', name: 'Golden Toad', provider: 'JBD', image: 'https://picsum.photos/seed/jbd4/400/600', category: 'স্লট', bgColor: 'from-green-500 to-green-800' },
  { id: 'jbd_5', name: 'Lucky Lion', provider: 'JBD', image: 'https://picsum.photos/seed/jbd5/400/600', category: 'স্লট', bgColor: 'from-red-600 to-red-900' },
  { id: 'jbd_6', name: 'Dragon Ball', provider: 'JBD', image: 'https://picsum.photos/seed/jbd6/400/600', category: 'স্লট', bgColor: 'from-orange-500 to-orange-800' },
  { id: 'jbd_7', name: 'Wealth God', provider: 'JBD', image: 'https://picsum.photos/seed/jbd7/400/600', category: 'স্লট', bgColor: 'from-yellow-600 to-yellow-900' },
  { id: 'jbd_8', name: 'Prosperity', provider: 'JBD', image: 'https://picsum.photos/seed/jbd8/400/600', category: 'স্লট', bgColor: 'from-blue-500 to-blue-800' },
  { id: 'jbd_9', name: 'Wukong', provider: 'JBD', image: 'https://picsum.photos/seed/jbd9/400/600', category: 'স্লট', isHot: true, bgColor: 'from-orange-600 to-red-800' },
  { id: 'jbd_10', name: 'Caishen', provider: 'JBD', image: 'https://picsum.photos/seed/jbd10/400/600', category: 'স্লট', bgColor: 'from-red-500 to-red-800' },
  { id: 'jbd_11', name: 'Fruit King', provider: 'JBD', image: 'https://picsum.photos/seed/jbd11/400/600', category: 'স্লট', bgColor: 'from-green-500 to-green-800' },
  { id: 'jbd_12', name: 'Ocean World', provider: 'JBD', image: 'https://picsum.photos/seed/jbd12/400/600', category: 'স্লট', bgColor: 'from-blue-400 to-blue-700' },
  { id: 'jbd_13', name: 'Super Joker', provider: 'JBD', image: 'https://picsum.photos/seed/jbd13/400/600', category: 'স্লট', bgColor: 'from-purple-500 to-purple-800' },
  { id: 'jbd_14', name: 'Diamond Fever', provider: 'JBD', image: 'https://picsum.photos/seed/jbd14/400/600', category: 'স্লট', isHot: true, bgColor: 'from-teal-400 to-teal-700' },
  { id: 'jbd_15', name: 'Viking Age', provider: 'JBD', image: 'https://picsum.photos/seed/jbd15/400/600', category: 'স্লট', bgColor: 'from-gray-600 to-gray-900' },
  { id: 'jbd_16', name: 'Egyptian Gold', provider: 'JBD', image: 'https://picsum.photos/seed/jbd16/400/600', category: 'স্লট', bgColor: 'from-yellow-400 to-yellow-700' },
  { id: 'jbd_17', name: 'Mystic Lake', provider: 'JBD', image: 'https://picsum.photos/seed/jbd17/400/600', category: 'স্লট', bgColor: 'from-blue-600 to-blue-900' },
  { id: 'jbd_18', name: 'Wild West', provider: 'JBD', image: 'https://picsum.photos/seed/jbd18/400/600', category: 'স্লট', isHot: true, bgColor: 'from-brown-600 to-orange-800' },

  // SPRIBE (18)
  { id: 'rocket_1', name: 'Space Rocket', provider: 'SPRIBE', image: 'https://picsum.photos/seed/rocket1/400/600', category: 'ক্র্যাশ', isHot: true, bgColor: 'from-blue-900 to-indigo-950' },
  { id: 'spribe_2', name: 'Mines', provider: 'SPRIBE', image: 'https://picsum.photos/seed/spribe2/400/600', category: 'মিনি গেম', bgColor: 'from-blue-600 to-blue-900' },
  { id: 'spribe_3', name: 'Dice', provider: 'SPRIBE', image: 'https://picsum.photos/seed/spribe3/400/600', category: 'মিনি গেম', bgColor: 'from-purple-500 to-purple-800' },
  { id: 'spribe_4', name: 'Mini Roulette', provider: 'SPRIBE', image: 'https://picsum.photos/seed/spribe4/400/600', category: 'মিনি গেম', bgColor: 'from-green-600 to-green-900' },
  { id: 'spribe_5', name: 'HiLo', provider: 'SPRIBE', image: 'https://picsum.photos/seed/spribe5/400/600', category: 'মিনি গেম', bgColor: 'from-red-500 to-red-800' },
  { id: 'spribe_6', name: 'Plinko', provider: 'SPRIBE', image: 'https://picsum.photos/seed/spribe6/400/600', category: 'মিনি গেম', bgColor: 'from-pink-500 to-pink-800' },
  { id: 'spribe_7', name: 'Goal', provider: 'SPRIBE', image: 'https://picsum.photos/seed/spribe7/400/600', category: 'মিনি গেম', bgColor: 'from-green-500 to-green-800' },
  { id: 'spribe_8', name: 'Keno', provider: 'SPRIBE', image: 'https://picsum.photos/seed/spribe8/400/600', category: 'মিনি গেম', bgColor: 'from-yellow-600 to-yellow-900' },
  { id: 'spribe_9', name: 'Balloon', provider: 'SPRIBE', image: 'https://picsum.photos/seed/spribe9/400/600', category: 'মিনি গেম', isHot: true, bgColor: 'from-blue-400 to-blue-700' },
  { id: 'spribe_10', name: 'Coin Field', provider: 'SPRIBE', image: 'https://picsum.photos/seed/spribe10/400/600', category: 'মিনি গেম', bgColor: 'from-yellow-500 to-yellow-800' },
  { id: 'spribe_11', name: 'Scratch', provider: 'SPRIBE', image: 'https://picsum.photos/seed/spribe11/400/600', category: 'মিনি গেম', bgColor: 'from-orange-500 to-orange-800' },
  { id: 'spribe_12', name: 'Lucky Plane', provider: 'SPRIBE', image: 'https://picsum.photos/seed/spribe12/400/600', category: 'ক্র্যাশ', bgColor: 'from-red-600 to-red-900' },
  { id: 'spribe_13', name: 'Turbo Mines', provider: 'SPRIBE', image: 'https://picsum.photos/seed/spribe13/400/600', category: 'মিনি গেম', isHot: true, bgColor: 'from-blue-600 to-indigo-900' },
  { id: 'spribe_14', name: 'Neon Dice', provider: 'SPRIBE', image: 'https://picsum.photos/seed/spribe14/400/600', category: 'মিনি গেম', bgColor: 'from-purple-400 to-purple-700' },
  { id: 'spribe_15', name: 'Space Hunt', provider: 'SPRIBE', image: 'https://picsum.photos/seed/spribe15/400/600', category: 'ক্র্যাশ', bgColor: 'from-indigo-700 to-black' },
  { id: 'spribe_16', name: 'Speed Roll', provider: 'SPRIBE', image: 'https://picsum.photos/seed/spribe16/400/600', category: 'মিনি গেম', bgColor: 'from-teal-500 to-teal-800' },
  { id: 'spribe_17', name: 'Tower', provider: 'SPRIBE', image: 'https://picsum.photos/seed/spribe17/400/600', category: 'মিনি গেম', bgColor: 'from-green-600 to-green-900' },
  { id: 'spribe_18', name: 'Crystal', provider: 'SPRIBE', image: 'https://picsum.photos/seed/spribe18/400/600', category: 'মিনি গেম', bgColor: 'from-cyan-400 to-blue-600' },

  // BT GAME (18)
  { id: 'bt_1', name: 'BT Slot 1', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt1/400/600', category: 'স্লট', bgColor: 'from-gray-700 to-gray-900' },
  { id: 'bt_2', name: 'BT Slot 2', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt2/400/600', category: 'স্লট', bgColor: 'from-blue-700 to-blue-900' },
  { id: 'bt_3', name: 'BT Slot 3', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt3/400/600', category: 'স্লট', bgColor: 'from-red-700 to-red-900' },
  { id: 'bt_4', name: 'BT Slot 4', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt4/400/600', category: 'স্লট', bgColor: 'from-green-700 to-green-900' },
  { id: 'bt_5', name: 'BT Slot 5', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt5/400/600', category: 'স্লট', bgColor: 'from-purple-700 to-purple-900' },
  { id: 'bt_6', name: 'BT Slot 6', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt6/400/600', category: 'স্লট', bgColor: 'from-yellow-700 to-yellow-900' },
  { id: 'bt_7', name: 'BT Slot 7', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt7/400/600', category: 'স্লট', bgColor: 'from-pink-700 to-pink-900' },
  { id: 'bt_8', name: 'BT Slot 8', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt8/400/600', category: 'স্লট', bgColor: 'from-indigo-700 to-indigo-900' },
  { id: 'bt_9', name: 'Golden Luck', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt9/400/600', category: 'স্লট', bgColor: 'from-yellow-400 to-yellow-700' },
  { id: 'bt_10', name: 'Wild Safari', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt10/400/600', category: 'স্লট', bgColor: 'from-green-600 to-green-900' },
  { id: 'bt_11', name: 'Thunder Strike', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt11/400/600', category: 'স্লট', isHot: true, bgColor: 'from-blue-500 to-blue-800' },
  { id: 'bt_12', name: 'Royal Gems', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt12/400/600', category: 'স্লট', bgColor: 'from-purple-600 to-purple-900' },
  { id: 'bt_13', name: 'Ocean Treasure', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt13/400/600', category: 'স্লট', bgColor: 'from-blue-400 to-blue-700' },
  { id: 'bt_14', name: 'Magic Forest', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt14/400/600', category: 'স্লট', bgColor: 'from-teal-500 to-teal-800' },
  { id: 'bt_15', name: 'Fire Dragon', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt15/400/600', category: 'স্লট', isHot: true, bgColor: 'from-red-500 to-red-800' },
  { id: 'bt_16', name: 'Frozen King', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt16/400/600', category: 'স্লট', bgColor: 'from-cyan-600 to-white/10' },
  { id: 'bt_17', name: 'Night Owl', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt17/400/600', category: 'স্লট', bgColor: 'from-gray-800 to-black' },
  { id: 'bt_18', name: 'Phoenix Wing', provider: 'BT GAME', image: 'https://picsum.photos/seed/bt18/400/600', category: 'স্লট', bgColor: 'from-orange-500 to-red-700' },

  // EVOLUTION (14)
  { id: 'evo_1', name: 'Crazy Time', provider: 'EVOLUTION', image: 'https://picsum.photos/seed/evo1/400/600', category: 'Live Casino', isHot: true, bgColor: 'from-purple-600 to-pink-600' },
  { id: 'evo_2', name: 'Lightning Roulette', provider: 'EVOLUTION', image: 'https://picsum.photos/seed/evo2/400/600', category: 'Live Casino', isHot: true, bgColor: 'from-yellow-600 to-red-600' },
  { id: 'evo_3', name: 'Monopoly Live', provider: 'EVOLUTION', image: 'https://picsum.photos/seed/evo3/400/600', category: 'Live Casino', bgColor: 'from-blue-600 to-blue-900' },
  { id: 'evo_4', name: 'Baccarat', provider: 'EVOLUTION', image: 'https://picsum.photos/seed/evo4/400/600', category: 'Live Casino', bgColor: 'from-green-600 to-green-900' },
  { id: 'evo_5', name: 'Mega Ball', provider: 'EVOLUTION', image: 'https://picsum.photos/seed/evo5/400/600', category: 'Live Casino', isHot: true, bgColor: 'from-blue-500 to-blue-800' },
  { id: 'evo_6', name: 'Super Sic Bo', provider: 'EVOLUTION', image: 'https://picsum.photos/seed/evo6/400/600', category: 'Live Casino', bgColor: 'from-red-600 to-red-900' },
  { id: 'evo_7', name: 'Dream Catcher', provider: 'EVOLUTION', image: 'https://picsum.photos/seed/evo7/400/600', category: 'Live Casino', isHot: true, bgColor: 'from-yellow-400 to-yellow-700' },
  { id: 'evo_8', name: 'Lightning Dice', provider: 'EVOLUTION', image: 'https://picsum.photos/seed/evo8/400/600', category: 'Live Casino', bgColor: 'from-orange-500 to-orange-800' },
  { id: 'evo_9', name: 'Fan Tan', provider: 'EVOLUTION', image: 'https://picsum.photos/seed/evo9/400/600', category: 'Live Casino', bgColor: 'from-green-700 to-green-900' },
  { id: 'evo_10', name: 'Craps', provider: 'EVOLUTION', image: 'https://picsum.photos/seed/evo10/400/600', category: 'Live Casino', bgColor: 'from-gray-700 to-black' },
  { id: 'evo_11', name: 'Dragon Tiger Live', provider: 'EVOLUTION', image: 'https://picsum.photos/seed/evo11/400/600', category: 'Live Casino', bgColor: 'from-red-700 to-red-900' },
  { id: 'evo_12', name: 'Mega Roulette', provider: 'EVOLUTION', image: 'https://picsum.photos/seed/evo12/400/600', category: 'Live Casino', isHot: true, bgColor: 'from-blue-600 to-indigo-800' },
  { id: 'evo_13', name: 'Blackjack Party', provider: 'EVOLUTION', image: 'https://picsum.photos/seed/evo13/400/600', category: 'Live Casino', bgColor: 'from-purple-500 to-purple-800' },
  { id: 'evo_14', name: 'Double Ball', provider: 'EVOLUTION', image: 'https://picsum.photos/seed/evo14/400/600', category: 'Live Casino', bgColor: 'from-yellow-600 to-yellow-900' },

  // Table Games (13)
  { id: 'table_1', name: 'Blackjack', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/table1/400/600', category: 'Table Games', bgColor: 'from-green-700 to-green-900' },
  { id: 'pp_super_acex', name: 'super Acex', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/super_acex/400/600', category: 'স্লট', isHot: true, bgColor: 'from-yellow-600 to-green-600', link: 'https://h5game-bs.victor-win.website:443/play/?icon-VA&language=en-US&token=49fd0655a15e4d8aadb8b78b7932c6aa' },
  { id: 'table_2', name: 'Roulette', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/table2/400/600', category: 'Table Games', bgColor: 'from-red-700 to-red-900' },
  { id: 'table_3', name: 'Baccarat', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/table3/400/600', category: 'Table Games', bgColor: 'from-blue-700 to-blue-900' },
  { id: 'table_4', name: 'Andar Bahar', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/table4/400/600', category: 'Table Games', isHot: true, bgColor: 'from-yellow-600 to-yellow-900' },
  { id: 'table_5', name: 'Teen Patti', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/table5/400/600', category: 'Table Games', isHot: true, bgColor: 'from-red-600 to-red-900' },
  { id: 'table_6', name: 'European Roulette', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/table6/400/600', category: 'Table Games', bgColor: 'from-green-600 to-green-900' },
  { id: 'table_7', name: 'Multihand Blackjack', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/table7/400/600', category: 'Table Games', bgColor: 'from-blue-600 to-blue-950' },
  { id: 'table_8', name: 'Poker', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/table8/400/600', category: 'Table Games', bgColor: 'from-gray-700 to-black' },
  { id: 'table_9', name: 'Speed Baccarat', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/table9/400/600', category: 'Table Games', bgColor: 'from-teal-500 to-teal-800' },
  { id: 'table_10', name: 'Dragon Tiger', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/table10/400/600', category: 'Table Games', bgColor: 'from-orange-600 to-red-800' },
  { id: 'table_11', name: 'Sic Bo', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/table11/400/600', category: 'Table Games', bgColor: 'from-yellow-500 to-orange-600' },
  { id: 'table_12', name: 'Jackpot Cards', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/table12/400/600', category: 'Table Games', bgColor: 'from-blue-400 to-indigo-900' },
  { id: 'table_13', name: 'Super 6', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/table13/400/600', category: 'Table Games', bgColor: 'from-purple-500 to-purple-800' },

  // Fishing Games (13)
  { id: 'fish_1', name: 'Mega Fishing', provider: 'JILI', image: 'https://picsum.photos/seed/fish1/400/600', category: 'Fishing Games', isHot: true, bgColor: 'from-blue-400 to-blue-700' },
  { id: 'fish_2', name: 'Jackpot Fishing', provider: 'JILI', image: 'https://picsum.photos/seed/fish2/400/600', category: 'Fishing Games', bgColor: 'from-cyan-500 to-blue-600' },
  { id: 'fish_3', name: 'Happy Fishing', provider: 'JILI', image: 'https://picsum.photos/seed/fish3/400/600', category: 'Fishing Games', bgColor: 'from-teal-500 to-teal-800' },
  { id: 'fish_4', name: 'Dinosaur Tycoon', provider: 'JILI', image: 'https://picsum.photos/seed/fish4/400/600', category: 'Fishing Games', isHot: true, bgColor: 'from-green-600 to-green-900' },
  { id: 'fish_5', name: 'Boom Legend', provider: 'JILI', image: 'https://picsum.photos/seed/fish5/400/600', category: 'Fishing Games', bgColor: 'from-orange-600 to-red-900' },
  { id: 'fish_6', name: 'Royal Fishing', provider: 'JILI', image: 'https://picsum.photos/seed/fish6/400/600', category: 'Fishing Games', bgColor: 'from-blue-600 to-blue-900' },
  { id: 'fish_7', name: 'Ocean King', provider: 'JILI', image: 'https://picsum.photos/seed/fish7/400/600', category: 'Fishing Games', isHot: true, bgColor: 'from-cyan-500 to-cyan-800' },
  { id: 'fish_8', name: 'Shark Hunter', provider: 'JILI', image: 'https://picsum.photos/seed/fish8/400/600', category: 'Fishing Games', bgColor: 'from-blue-700 to-black' },
  { id: 'fish_9', name: 'Golden Shark', provider: 'JILI', image: 'https://picsum.photos/seed/fish9/400/600', category: 'Fishing Games', bgColor: 'from-yellow-500 to-yellow-800' },
  { id: 'fish_10', name: 'All-star Fishing', provider: 'JILI', image: 'https://picsum.photos/seed/fish10/400/600', category: 'Fishing Games', bgColor: 'from-purple-500 to-purple-800' },
  { id: 'fish_11', name: 'Fishermans Life', provider: 'JILI', image: 'https://picsum.photos/seed/fish11/400/600', category: 'Fishing Games', bgColor: 'from-teal-400 to-teal-700' },
  { id: 'fish_12', name: 'Deep Sea Hunter', provider: 'JILI', image: 'https://picsum.photos/seed/fish12/400/600', category: 'Fishing Games', bgColor: 'from-blue-900 to-black' },
  { id: 'fish_13', name: 'Bombing Fishing', provider: 'JILI', image: 'https://picsum.photos/seed/fish13/400/600', category: 'Fishing Games', bgColor: 'from-red-500 to-red-800' },

  // Lottery (12)
  { id: 'lottery_1', name: 'Keno', provider: 'SPRIBE', image: 'https://picsum.photos/seed/lottery1/400/600', category: 'Lottery', bgColor: 'from-yellow-500 to-orange-600' },
  { id: 'lottery_2', name: 'Bingo', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/lottery2/400/600', category: 'Lottery', bgColor: 'from-pink-500 to-purple-600' },
  { id: 'lottery_3', name: 'Luck 5', provider: 'SPRIBE', image: 'https://picsum.photos/seed/lottery3/400/600', category: 'Lottery', bgColor: 'from-teal-500 to-teal-800' },
  { id: 'lottery_4', name: 'Fortune 6', provider: 'SPRIBE', image: 'https://picsum.photos/seed/lottery4/400/600', category: 'Lottery', bgColor: 'from-yellow-500 to-yellow-800' },
  { id: 'lottery_5', name: 'Classic Bingo', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/lottery5/400/600', category: 'Lottery', isHot: true, bgColor: 'from-purple-600 to-purple-900' },
  { id: 'lottery_6', name: 'Speedy Lotto', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/lottery6/400/600', category: 'Lottery', bgColor: 'from-blue-600 to-blue-900' },
  { id: 'lottery_7', name: 'Golden Ball', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/lottery7/400/600', category: 'Lottery', bgColor: 'from-yellow-600 to-yellow-900' },
  { id: 'lottery_8', name: 'Color Game', provider: 'JILI', image: 'https://picsum.photos/seed/lottery8/400/600', category: 'Lottery', isHot: true, bgColor: 'from-red-500 to-orange-600' },
  { id: 'lottery_9', name: 'Instant Win', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/lottery9/400/600', category: 'Lottery', bgColor: 'from-green-600 to-green-900' },
  { id: 'lottery_10', name: 'Power Lotto', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/lottery10/400/600', category: 'Lottery', bgColor: 'from-blue-500 to-blue-800' },
  { id: 'lottery_11', name: 'Mega Millions', provider: 'PRAGMATIC', image: 'https://picsum.photos/seed/lottery11/400/600', category: 'Lottery', isHot: true, bgColor: 'from-indigo-600 to-indigo-900' },
  { id: 'lottery_12', name: 'Daily Draw', provider: 'SPRIBE', image: 'https://picsum.photos/seed/lottery12/400/600', category: 'Lottery', bgColor: 'from-teal-600 to-teal-900' },
];
