export const GAME_IMAGES = {
  AVIATOR_LOGO: "https://storage.googleapis.com/genai-studio-user-uploads/projects/ais-dev-wxllhxlbpwpt7cv6zg665n/uploads/1743526563604-image.png",
  CRASH_GAME: "https://picsum.photos/seed/crash/400/600",
  SUPER_ACE: "https://picsum.photos/seed/cards/400/600",
  SUPER_ACE_2: "https://picsum.photos/seed/poker/400/600",
  WG_PLANE: "https://picsum.photos/seed/airplane/400/600",
  CHICKEN_ROAD: "https://picsum.photos/seed/farm/400/600",
  CRAZY_TIME: "https://picsum.photos/seed/wheel/400/600",
  PG_GAME: "https://picsum.photos/seed/slots/400/600",
  MAGIC_ACE: "https://picsum.photos/seed/magic/400/600",
  ROULETTE: "https://picsum.photos/seed/roulette/400/600",
  DRAGON_TIGER: "https://picsum.photos/seed/dragon/400/600",
  FISH_HUNTER: "https://picsum.photos/seed/ocean/400/600",
  BOOK_OF_GOLD: "https://picsum.photos/seed/gold/400/600",
  MEGA_BALL: "https://picsum.photos/seed/bingo/400/600",
  SIC_BO: "https://picsum.photos/seed/dice/400/600",
  KONG_INVASION: "https://picsum.photos/seed/gorilla/400/600",
  CASINO_VIDEO_URL: "https://assets.mixkit.co/videos/preview/mixkit-luxury-casino-interior-with-roulette-table-31411-large.mp4",
  SLOT_VIDEO_URL: "https://assets.mixkit.co/videos/preview/mixkit-slot-machine-close-up-in-a-casino-39855-large.mp4"
};
